### ISSUE TITLE
main.go doesn't work

### ISSUE THREAD

**Issue by mnickw** [Skyuzii/SpoofingTlsFingerprint#4]
I have an error: listen tcp: lookup tcp/port: getaddrinfow: The specified class was not found. 
![Screenshot 2022-10-25 212412](https://user-images.githubusercontent.com/57790664/197852958-5b74e29d-0f96-4500-be1b-01929f8fa482.png)

my telegram: @mnickw

**Comment by mnickw** [comment]
In debug in vs code it works for some reason, I checked localhost:8000/check-status, it is "good"
![Screenshot 2022-10-25 235659](https://user-images.githubusercontent.com/57790664/197880426-f92d1dea-d2dc-4997-acd0-b3b009085c20.png)

**Comment by Skyuzii** [comment]
Hello! Thanks for this issue.

Instead of the word port, you need to specify a port of numbers ```go run main.go 7777```. If nothing is specified, then the default port is 8000

**Comment by mnickw** [comment]
ok, stupid mistake. Thanks for answer
